/* GramaticaCoco.java */
/* Generated By:JavaCC: Do not edit this line. GramaticaCoco.java */
package javacc;
import coco.Arbol;
import coco.Tabla;
import coco.Simbolo;
import coco.Colores;
import coco.Pila;
import java.util.List;


public class GramaticaCoco implements GramaticaCocoConstants {
  // tABLA DE SIMBOLOS GENERADA.
  private Tabla tabla = Tabla.getTabla();
  private Pila pilaSemantica = new Pila();
  private static java.util.List<String> listaErrores = new java.util.ArrayList<String>();
  private int profundidadSwitch = 0; // Para accion semantica, break solo en switch. 


  // Getter para la pila
  public Pila getPilaSemantica()
  {
    return this.pilaSemantica;
  }

  public static void registrarError(String msj)
  {
    listaErrores.add(msj);
  }

  public java.util.List<String> getListaErrores()
  {
    return listaErrores;
  }


  /*-- RECUPERACION DE ERRORES SINTACTICOS --*/
  void recuperacionSintactica() throws ParseException {
    Token t;
    while (true) {
        t = getToken(1);
        if (t.kind == EOF) break; // Si es fin de archivo, parar

        // Si encontramos un punto y coma, lo consumimos y salimos
        if (t.kind == PUNTOYCOMA) {
            consumeToken(PUNTOYCOMA);
            return;
        }

        // Si encontramos una llave de cierre, NO la consumimos (pertenece al bloque padre)
        // pero salimos para que el bloque padre se encargue.
        if (t.kind == LLAVE_CIERRA || t.kind == FINAL) {
            return;
        }

          if (t.kind == ELSE) {
            return;
        }

        // Si encontramos el inicio de otra sentencia, paramos ahí para parsear la siguente
        if (t.kind == VAR || t.kind == IF || t.kind == BUCLE_FOR ||
            t.kind == BUCLE_WHILE || t.kind == SWITCH || t.kind == RETURN ||
            t.kind == SALIDA || t.kind == ENTRADA || t.kind == ID || t.kind == FUNC) {
            return;
        }

        // Si no es nada anterior, detodas maneras se consume para seguir avanzando
        consumeToken(t.kind);
    }
  }

  void consumeToken(int kind) throws ParseException {
    jj_consume_token(kind);
  }



  /*-- METODOS PARA COMPROBAR TIPODS --*/

  public String obtenerTipoDeArbol(Arbol nodo)
  {
    if (nodo == null) return "error";

    String nombre = nodo.getNombreProduccion();

    // 1. Caso Base: Literales (hojas del árbol)
    if (nombre.startsWith("Literal_INT")) return "int";
    if (nombre.startsWith("Literal_FLOAT")) return "float";
    if (nombre.startsWith("Literal_CADENA_DE_CARACTERES")) return "string";
    if (nombre.startsWith("Literal_BOOL")) return "bool";
    // if (nombre.startsWith("Literal_BOOL")) return "bool";

    // 2. Caso Base: Identificadores (Variables)
    if (nombre.startsWith("Literal_IDENTIFICADOR"))
    {
        // Extraemos el nombre
        String[] partes = nombre.split(": ");
        if (partes.length < 2) return "error";

        String idNombre = partes[1].trim();
        Simbolo s = tabla.buscar(idNombre);

        if (s != null) {
            return s.tipo; // Devuelve el tipo,
        }
        return "error";
    }

    // 3. Caso: Llamada a Función
    if (nombre.equals("LlamadaFuncion")) {
        // El primer hijo es el ID...
        Arbol nodoId = nodo.getHijos().get(0);
        String idNombre = nodoId.getNombreProduccion().split(": ")[1].trim();
        Simbolo s = tabla.buscar(idNombre);

        if (s != null && s.tipo.equals("funcion")) {
           // return s.tipoRetorno; // Retornamos el tipo que devuelve la función
            return (s.tipoRetorno != null) ? s.tipoRetorno : "error"; // pero se checa si no es nullo,
        }
        return "error";
    }

    // 4. Caso: Agrupación (Paréntesis)
    if (nombre.equals("Agrupacion")) {
        // Estructura: Token (, Expresion, Token )
        // El hijo 1 es la expresión interna
        if (nodo.getHijos().size() > 1) {
            return obtenerTipoDeArbol(nodo.getHijos().get(1));
        }
        return "error";
    }

    // 5. Caso: Operadores Unarios (!, ++, --, -)
    if (nombre.startsWith("Unario_NOT")) {
        // El operador ! siempre devuelve bool
        // verificacion de tipos en op unarios !:
        Arbol hijo = nodo.getHijos().get(1);
        String tipoHijo = obtenerTipoDeArbol(hijo);

                // Verificacion de tipos en operador unario not, de tipo bool.
                if (!tipoHijo.equals("bool") && !tipoHijo.equals("error"))
                {
              registrarError("Error Sem\u00e1ntico: El operador '!' requiere un operando de tipo 'bool', se encontr\u00f3 '" + tipoHijo + "'.");
              return "error";
        }

        return "bool";
    }
    // cheque de tipos ++ o -- necesitan numeros.
    if (nombre.startsWith("Unario_INC") || nombre.startsWith("Unario_DEC"))
    {
        // ++, --, - (negativo) devuelven el mismo tipo del operando
        // Estructura: Token, Operando

                Arbol hijo = nodo.getHijos().get(1);
                String tipoHijo = obtenerTipoDeArbol(hijo);

                if (!tipoHijo.equals("int") && !tipoHijo.equals("float") && !tipoHijo.equals("error"))
                {
                  registrarError("Error Sem\u00e1ntico: Los operadores '++' o '--' requieren tipos num\u00e9ricos, se encontr\u00f3 '" + tipoHijo + "'.");
          return "error";
                }

                return tipoHijo;
    }

        // Caso 5.5
        // Cheque de tipoos, evita string negativas -"hola" XDXDXDXDXd.
    if (nombre.startsWith("Unario_RESTA"))
    {
      Arbol hijo = nodo.getHijos().get(1);
      String tipoHijo = obtenerTipoDeArbol(hijo);


          if (!tipoHijo.equals("int") && !tipoHijo.equals("float") && !tipoHijo.equals("error"))
          {
            registrarError("Error Sem\u00e1ntico: El operador unario '-' requiere tipos num\u00e9ricos, se encontr\u00f3 '" + tipoHijo + "'.");
        return "error";
          }

          return tipoHijo;

    }

    // 6. Caso: Operaciones Binarias (Aritméticas, Relacionales, Lógicas)
    // Estructura típica: [Izquierda, Token Operador, Derecha]
    if (nombre.startsWith("Operacion_") || nombre.startsWith("Operador_")) {
        List<Arbol> hijos = nodo.getHijos();
        if (hijos.size() < 3) return "error";

        Arbol izq = hijos.get(0);
        // Arbol op = hijos.get(1); // Token del operador
        Arbol der = hijos.get(2);

        String tipoIzq = obtenerTipoDeArbol(izq);
        String tipoDer = obtenerTipoDeArbol(der);

        // Si hay error en los operandos, propagamos el error
        if (tipoIzq.equals("error") || tipoDer.equals("error")) return "error";

        // Reglas de Inferencia de Tipos

        // A) Operaciones Aritméticas (+, -, *, /)
        if (nombre.contains("SUM_RES") || nombre.contains("MUL_DIV_MOD")) {
            // int + int = int
            if (tipoIzq.equals("int") && tipoDer.equals("int")) return "int";

            // float + int = float (promoción de tipo)
            if ((tipoIzq.equals("float") || tipoIzq.equals("int")) &&
                (tipoDer.equals("float") || tipoDer.equals("int"))) {
                return "float";
            }

            // String + X = String
            if (tipoIzq.equals("string") || tipoDer.equals("string")) return "string";

            // Si no coinciden, es error de tipos (ej: bool + int)
            registrarError("Error Sem\u00e1ntico: Operaci\u00f3n aritm\u00e9tica inv\u00e1lida entre tipos '" + tipoIzq + "' y '" + tipoDer + "'");
            return "error";
        }

        // B) Operaciones Relacionales (<, >, ==)
        if (nombre.contains("Relacional")) {
            // Comparar números
            if ((tipoIzq.equals("int") || tipoIzq.equals("float")) &&
                (tipoDer.equals("int") || tipoDer.equals("float"))) {
                return "bool";
            }
            // Comparar strings (solo igualdad/desigualdad usualmente)
            if (tipoIzq.equals("string") && tipoDer.equals("string")) {
                return "bool";
            }

            registrarError("Error Sem\u00e1ntico: No se pueden comparar tipos '" + tipoIzq + "' y '" + tipoDer + "'");
            return "error";
        }

        // C) Operaciones Lógicas (&&, ||)
        if (nombre.contains("AND") || nombre.contains("OR")) {
            if (tipoIzq.equals("bool") && tipoDer.equals("bool")) {
                return "bool";
            }
            registrarError("Error Sem\u00e1ntico: Operadores l\u00f3gicos requieren tipos 'bool', se encontr\u00f3 '" + tipoIzq + "' y '" + tipoDer + "'");
            return "error";
        }
    }

    return "error"; // Caso por defecto desconocido
  }

  // Variable para checar el tipo del retorno de una funcion.
  private String tipoRetornoFuncionActual = null;

  // Lista que guarda los tipos de los parametros durante el parseo.
  private java.util.List<String> tiposParametrosActuales = new java.util.ArrayList<>();



        /*-- PILA SEMANTICA --*/

  // Método para operadores binarios
  private void validarOperacionBinaria(Token op) {
      // Si la pila está vacía, no salimos
      if (pilaSemantica.estaVacia()) return;
      String tipoDer = (String) pilaSemantica.pop();

      if (pilaSemantica.estaVacia()) return;
      String tipoIzq = (String) pilaSemantica.pop();

      String tipoResultado = "error";

      // --- Lógica de Tipos (Aritmética, Relacional, Lógica) ---

      // Operadores Aritméticos (+, -, *, /, %)
      if (op.kind == OP_SUMA || op.kind == OP_RESTA || op.kind == OP_MULTI || op.kind == OP_DIVI || op.kind == OP_MOD) {
          if (tipoIzq.equals("int") && tipoDer.equals("int")) {
              tipoResultado = "int";
          } else if ((tipoIzq.equals("int") || tipoIzq.equals("float")) &&
                     (tipoDer.equals("int") || tipoDer.equals("float"))) {
              tipoResultado = "float";
          } else if (op.kind == OP_SUMA && (tipoIzq.equals("string") || tipoDer.equals("string"))) {
              tipoResultado = "string"; // Pa concatenacion
          } else {
              if (!tipoIzq.equals("error") && !tipoDer.equals("error")) {
                  registrarError("Error Sem\u00e1ntico: No se puede aplicar '" + op.image + "' entre tipos " + tipoIzq + " y " + tipoDer);
              }
          }
      }
      // Operadores Lógicos (&&, ||)
      else if (op.kind == OP_AND || op.kind == OP_OR) {
          if (tipoIzq.equals("bool") && tipoDer.equals("bool")) {
              tipoResultado = "bool";
          } else {
              if (!tipoIzq.equals("error") && !tipoDer.equals("error")) {
                  registrarError("Error Sem\u00e1ntico: Operador '" + op.image + "' requiere operandos bool.");
              }
          }
      }
      // Operadores Relacionales (<, >, ==, etc.)
      else if (op.kind == OP_MAYOR_QUE || op.kind == OP_MENOR_QUE || op.kind == OP_MAYOR_IGUAL ||
               op.kind == OP_MENOR_IGUAL || op.kind == OP_IGUALDAD || op.kind == OP_DESIGUALDAD) {
           // Comparación de números
           if ((tipoIzq.equals("int") || tipoIzq.equals("float")) &&
               (tipoDer.equals("int") || tipoDer.equals("float"))) {
               tipoResultado = "bool";
           }
           // Comparación de strings (igualdad/desigualdad)
           else if (tipoIzq.equals("string") && tipoDer.equals("string")) {
               tipoResultado = "bool";
           }
           else {
               if (!tipoIzq.equals("error") && !tipoDer.equals("error")) {
                   registrarError("Error Sem\u00e1ntico: No se pueden comparar tipos " + tipoIzq + " y " + tipoDer);
               }
           }
      }
    System.out.println( Colores.MORADO + "#DEBUG Pila: Op='" + op.image + "', Izq=" + tipoIzq + ", Der=" + tipoDer + " -> Res=" + tipoResultado);


      // Empujar el resultado a la pila
      pilaSemantica.push(tipoResultado);
  }

  final public Arbol Coco() throws ParseException {Arbol raiz = new Arbol("Ra\u00edz");
  Arbol fn, stmt;
  Token t_inicio, t_final;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case FUNC:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      try {
        fn = funcion();
raiz.agregarHijo(fn);
      } catch (ParseException e) {
Token errorTok = e.currentToken;
          registrarError("Error Sint\u00e1ctico: L\u00ednea " + errorTok.beginLine + ", columna " + errorTok.beginColumn +
          ". " + e.getMessage());
          recuperacionSintactica();
      }
    }
    t_inicio = jj_consume_token(INICIO);
raiz.agregarHijo(new Arbol("Token: " + t_inicio.image));
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case IF:
      case SWITCH:
      case BREAK:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case VAR:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      try {
        stmt = sentencia();
raiz.agregarHijo(stmt);
      } catch (ParseException e) {
Token errorTok = e.currentToken;
          registrarError("Error Sint\u00e1ctico: L\u00ednea " + errorTok.beginLine + ", columna " + errorTok.beginColumn +
          ". " + e.getMessage());
          recuperacionSintactica();
      }
    }
    t_final = jj_consume_token(FINAL);
raiz.agregarHijo(new Arbol("Token: " + t_final.image));
    jj_consume_token(0);
{if ("" != null) return raiz;}
    throw new Error("Missing return statement in function");
}

// Las funciones van antes de la funcion principal.
  final public Arbol funcion() throws ParseException {Arbol nodoFuncion = new Arbol("DeclaracionDeFuncion");
  String tipoRetorno, nombreFuncion;
  Arbol parametros, bloque;
  Token t_decl, t_id, t_flecha, t_pa, t_pc;
  Simbolo simboloFuncion = null; // Para la comprobacion de tipos en los pareametros de la funcion.

    t_decl = jj_consume_token(FUNC);
nodoFuncion.agregarHijo(new Arbol ("Token: " + t_decl.image));
    t_id = jj_consume_token(ID);
nodoFuncion.agregarHijo(new Arbol ("Token: " + t_id.image));
    nombreFuncion = t_id.image;
    t_flecha = jj_consume_token(FLECHA);
nodoFuncion.agregarHijo(new Arbol ("Token: " + t_flecha.image));
    tipoRetorno = tiposDeDatos();
nodoFuncion.agregarHijo(new Arbol("TipoRetorno: " + tipoRetorno));
/*Simbolo simboloFuncion = new Simbolo(nombreFuncion, "funcion", tabla.getAmbitoActual(), t_id.beginLine);
    tabla.insertar(simboloFuncion); */

    tipoRetornoFuncionActual = tipoRetorno;  // Para validar el tipo de retorno.

        simboloFuncion = new Simbolo(nombreFuncion, "funcion", tabla.getAmbitoActual(), t_id.beginLine);
    simboloFuncion.tipoRetorno = tipoRetorno;
    tabla.insertar(simboloFuncion);

    tiposParametrosActuales.clear(); // Se limpia la lista para evitar traer "basura" de otras funciones.    

    t_pa = jj_consume_token(PAREN_ABRE);
nodoFuncion.agregarHijo(new Arbol ("Token " + t_pa.image));
tabla.entrarAmbito(nombreFuncion);
    parametros = listaParametros();
nodoFuncion.agregarHijo(parametros);
simboloFuncion.parametros.addAll(tiposParametrosActuales);
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoFuncion.agregarHijo(new Arbol ("Token: " + t_pc.image));
    bloque = bloqueDeCodigo();
nodoFuncion.agregarHijo(bloque);
tabla.salirAmbito();
    tipoRetornoFuncionActual = null; // Limpiamos la variable; Por si se encuentra otra declaracion de funcion
        {if ("" != null) return nodoFuncion;}
    throw new Error("Missing return statement in function");
}

// Produccion que define la lista de parametros de una funcion.
  final public Arbol listaParametros() throws ParseException {Arbol nodoListaDeParametros = new Arbol("ListaDeParametros");
  Arbol param;
  Token t_coma;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:
    case FLOTANTE:
    case BOOLEANO:
    case CHAR:
    case STRING:{
      param = parametro();
nodoListaDeParametros.agregarHijo(param);
      label_3:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[2] = jj_gen;
          break label_3;
        }
        t_coma = jj_consume_token(COMA);
nodoListaDeParametros.agregarHijo(new Arbol ("Token: " + t_coma.image));
        param = parametro();
nodoListaDeParametros.agregarHijo(param);
      }
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
{if ("" != null) return nodoListaDeParametros;}
    throw new Error("Missing return statement in function");
}

// Produccion que define solo un parametro.
  final public Arbol parametro() throws ParseException {Arbol nodoParametro = new Arbol("ParametroIndividual");
  Token t_dos_puntos, t_id;
  String tipoDato;
    tipoDato = tiposDeDatos();
nodoParametro.agregarHijo(new Arbol("Tipo: " + tipoDato));
    tiposParametrosActuales.add(tipoDato); // para la Validacion de parametros en funciones

    t_dos_puntos = jj_consume_token(DOSPUNTOS);
nodoParametro.agregarHijo(new Arbol ("Token: " + t_dos_puntos.image));
    t_id = jj_consume_token(ID);
nodoParametro.agregarHijo(new Arbol ("Token: " + t_id.image));
    Simbolo nuevoParametro = new Simbolo(t_id.image, tipoDato, tabla.getAmbitoActual(), t_id.beginLine);
    tabla.insertar(nuevoParametro);
{if ("" != null) return nodoParametro;}
    throw new Error("Missing return statement in function");
}

// Produccion que define todo el codigo que se encuentra entre llaves.
// -> Su scope debe ser de 1.
  final public Arbol bloqueDeCodigo() throws ParseException {Arbol nodoBloque = new Arbol("BloqueDeCodigo");
  Arbol sentencia;
  Token t_llave_a, t_llave_c;
    t_llave_a = jj_consume_token(LLAVE_ABRE);
nodoBloque.agregarHijo(new Arbol ("Token: " + t_llave_a.image));
    tabla.entrarAmbito("bloque_" + t_llave_a.beginLine);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case IF:
      case SWITCH:
      case BREAK:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case VAR:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      try {
        sentencia = sentencia();
nodoBloque.agregarHijo(sentencia);
      } catch (ParseException e) {
Token errorTok = e.currentToken;
      registrarError("Error Sint\u00e1ctico: L\u00ednea " + errorTok.beginLine + ", columna " + errorTok.beginColumn +
      ". " + e.getMessage());
      recuperacionSintactica();
      }
    }
    t_llave_c = jj_consume_token(LLAVE_CIERRA);
nodoBloque.agregarHijo(new Arbol ("Token: " + t_llave_c.image));
        tabla.salirAmbito();
{if ("" != null) return nodoBloque;}
    throw new Error("Missing return statement in function");
}

// Produccion que define las sentencias "simples"
  final public Arbol sentencia() throws ParseException {Arbol s;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR:{
      s = declaracionDeVariable();
{if ("" != null) return s;}
      break;
      }
    case ENTERO:
    case FLOTANTE:
    case BOOLEANO:
    case CHAR:
    case STRING:{
      s = declaracionVector();
{if ("" != null) return s;}
      break;
      }
    case SALIDA:{
      s = salida();
{if ("" != null) return s;}
      break;
      }
    case ENTRADA:{
      s = entrada();
{if ("" != null) return s;}
      break;
      }
    case BUCLE_FOR:{
      s = bucleFor();
{if ("" != null) return s;}
      break;
      }
    case BUCLE_WHILE:{
      s = bucleWhile();
{if ("" != null) return s;}
      break;
      }
    case IF:{
      s = condicionalIf();
{if ("" != null) return s;}
      break;
      }
    case SWITCH:{
      s = condicionalSwitch();
{if ("" != null) return s;}
      break;
      }
    case RETURN:{
      s = sentenciaRetorno();
{if ("" != null) return s;}
      break;
      }
    case ID:{
      s = sentenciasConIdentificador();
{if ("" != null) return s;}
      break;
      }
    case BREAK:{
      s = sentenciaBreak();
{if ("" != null) return s;}
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public Arbol sentenciasConIdentificador() throws ParseException {Arbol nodo = new Arbol("SentenciasConIdentificador");
  Arbol llamadaFunc, accVector, exp;
  Token t_pc, t_asig, t_id;
  Simbolo simboloUsado = null;

  String tipoLadoIzquierdo;
  String tipoLadoDerecho;
    if (jj_2_1(3)) {
      llamadaFunc = llamadaFuncion();
nodo.agregarHijo(llamadaFunc);
      t_pc = jj_consume_token(PUNTOYCOMA);
nodo.agregarHijo(new Arbol ("Token: " + t_pc.image));
if (!pilaSemantica.estaVacia())
      {
          pilaSemantica.pop();
      }
      {if ("" != null) return nodo;}
    } else if (jj_2_2(3)) {
      accVector = accesoVector();
nodo.agregarHijo(accVector);
      // accesoVector ya empujó (push) el tipo de los elementos del vector a la pila.

      t_asig = jj_consume_token(OP_ASIGNACION);
nodo.agregarHijo(new Arbol("Token: " + t_asig.image));
      exp = expresion();
// La expresión empujó (push) su tipo resultado.

      // Sacamos el tipo de la expresión (lado derecho)
      tipoLadoDerecho = "error";
      if (!pilaSemantica.estaVacia()) {
          tipoLadoDerecho = (String) pilaSemantica.pop();
      }

      // Sacamos el tipo del vector (lado izquierdo, empujado por accesoVector)
      tipoLadoIzquierdo = "error";
      if (!pilaSemantica.estaVacia()) {
          tipoLadoIzquierdo = (String) pilaSemantica.pop();
      }

      // Validación de Tipos
      if (!tipoLadoDerecho.equals("error") && !tipoLadoIzquierdo.equals("error"))
      {
         boolean esCompatible = tipoLadoIzquierdo.equals(tipoLadoDerecho) ||
                              (tipoLadoIzquierdo.equals("float") && tipoLadoDerecho.equals("int"));

         if (!esCompatible)
         {
           registrarError("Error Sem\u00e1ntico: L\u00ednea " + t_asig.beginLine + ". No se puede asignar tipo '" + tipoLadoDerecho +
                          "' al vector que es de tipo '" + tipoLadoIzquierdo + "'.");
         }
      }

      nodo.agregarHijo(exp);
      t_pc = jj_consume_token(PUNTOYCOMA);
nodo.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodo;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        t_id = jj_consume_token(ID);
nodo.agregarHijo(new Arbol("ID_Asignacion: " + t_id.image));
      simboloUsado = tabla.buscar(t_id.image);

      if (simboloUsado == null)
        {
          registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ", columna " + t_id.beginColumn +
          " La variable '" + t_id.image + "' no ha sido declarada.");
          tipoLadoIzquierdo = "error";
        }
        else
        {
          tipoLadoIzquierdo = simboloUsado.tipo;
        }
        t_asig = jj_consume_token(OP_ASIGNACION);
nodo.agregarHijo(new Arbol("Token: " + t_asig.image));
        exp = expresion();
// La expresión empujó (push) su tipo resultado.

      // Sacamos el tipo de la expresión (lado derecho)
      tipoLadoDerecho = "error";
      if (!pilaSemantica.estaVacia()) {
          tipoLadoDerecho = (String) pilaSemantica.pop();
      }

      // Validación de Tipos usando la variable local tipoLadoIzquierdo
      if (!tipoLadoDerecho.equals("error") && !tipoLadoIzquierdo.equals("error"))
      {
        if (!tipoLadoIzquierdo.equals(tipoLadoDerecho))
        {
          boolean esCompatible = (tipoLadoIzquierdo.equals("float") && tipoLadoDerecho.equals("int"));

          if (!esCompatible)
          {
            registrarError("Error Sem\u00e1ntico: L\u00ednea " + t_id.beginLine + ". Tipos incompatibles. No se puede asignar '" + tipoLadoDerecho + "' a variable de tipo '" + tipoLadoIzquierdo + "'");
          }
        }
      }

      nodo.agregarHijo(exp);
        t_pc = jj_consume_token(PUNTOYCOMA);
nodo.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodo;}
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

// Return...
  final public Arbol sentenciaRetorno() throws ParseException {Arbol nodoRetorno = new Arbol("SentenciaDeRetorno");
  Arbol exp;
  Token t_return, t_pc;
    t_return = jj_consume_token(RETURN);
nodoRetorno.agregarHijo(new Arbol ("Token: " + t_return.image));
    exp = expresion();
nodoRetorno.agregarHijo(exp);
String tipoExp = "error";
  if (!pilaSemantica.estaVacia())
  {
      tipoExp = (String) pilaSemantica.pop();
  }
    if (tipoRetornoFuncionActual != null )
    {
      //String tipoExp = obtenerTipoDeArbol(exp);

      boolean esCompatible = tipoExp.equals(tipoRetornoFuncionActual) || (tipoRetornoFuncionActual.equals("float") && tipoExp.equals("int"));

      if (!esCompatible && !tipoExp.equals("error"))
      {
        registrarError("Error Semantico: Linea " + t_return.beginLine + ", columna " + t_return.beginColumn + ". El tipo de retorno '" + tipoExp +
        "' no coincide con el tipo declarado  de la funcion: '" + tipoRetornoFuncionActual + "'");
      }

    }
    t_pc = jj_consume_token(PUNTOYCOMA);
nodoRetorno.agregarHijo(new Arbol ("Token: " + t_pc.image));
{if ("" != null) return nodoRetorno;}
    throw new Error("Missing return statement in function");
}

  final public Arbol llamadaFuncion() throws ParseException {Arbol nodoLlamadaFuncion = new Arbol("LlamadaFuncion");
  Arbol exp;
  Token t_id, t_pa, t_pc, t_coma;
  java.util.List<String> tiposArgumentos = new java.util.ArrayList<>();

  // Variables para validación y pila
  Simbolo simbolo = null;
  String tipoRetorno = "error";
  String tipoArg = "error";
    t_id = jj_consume_token(ID);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_id.image));

    simbolo = tabla.buscar(t_id.image);
    if (simbolo == null)
    {
      registrarError("Error Semantico: L\u00ednea " + t_id.beginLine +  ", columna " + t_id.beginColumn + " La funci\u00f3n '" + t_id.image + "' no ha sido declarada.");
    }
    else if (!simbolo.tipo.equals("funcion"))
    {
      registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ", columna " + t_id.beginColumn + " El identificador '" + t_id.image
      + "' no es una funci\u00f3n (es de tipo '" + simbolo.tipo + "').");
      simbolo = null; // Invalidamos para no validar argumentos abajo
    }
    else
    {
      // Si existe y es función, guardamos su tipo de retorno
      tipoRetorno = (simbolo.tipoRetorno != null) ? simbolo.tipoRetorno : "error";
    }
    t_pa = jj_consume_token(PAREN_ABRE);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_pa.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OP_RESTA:
    case OP_INCREMENTO:
    case OP_DECREMENTO:
    case OP_NOT:
    case PAREN_ABRE:
    case NUM_FLOTANTE:
    case NUM_ENTERO:
    case TRUE:
    case FALSE:
    case ID:
    case STR:{
      exp = expresion();
nodoLlamadaFuncion.agregarHijo(exp);

      // 1. POP: Sacamos el tipo que la expresión dejó en la pila
      tipoArg = "error";
      if (!pilaSemantica.estaVacia()) {
          tipoArg = (String) pilaSemantica.pop();
      }

      // 2. Guardamos ese tipo en la lista para validar contra los parámetros
      tiposArgumentos.add(tipoArg);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMA:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_5;
        }
        t_coma = jj_consume_token(COMA);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_coma.image));
        exp = expresion();
nodoLlamadaFuncion.agregarHijo(exp);

        // Repetimos la lógica para los siguientes argumentos
        tipoArg = "error";
        if (!pilaSemantica.estaVacia()) {
            tipoArg = (String) pilaSemantica.pop();
        }
        tiposArgumentos.add(tipoArg);
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoLlamadaFuncion.agregarHijo(new Arbol ("Token: " + t_pc.image));
if (simbolo != null)
    {
      int numEsperados = simbolo.parametros.size();
      int numActuales = tiposArgumentos.size();

      if (numActuales != numEsperados)
      {
        registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ". La funci\u00f3n '" + t_id.image +
        "' espera " + numEsperados + " argumentos, pero se encontraron " + numActuales + ".");
      }
      else
      {
        // Validamos tipos uno por uno
        for (int i = 0; i < numActuales; i++)
        {
          String tipoEsp = simbolo.parametros.get(i);
          String tipoAct = tiposArgumentos.get(i);

          boolean compatible = tipoEsp.equals(tipoAct) || (tipoEsp.equals("float") && tipoAct.equals("int"));

          if (!compatible && !tipoAct.equals("error"))
          {
            registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ". En la llamada a '" +
            t_id.image + "', el argumento #" + (i+1) + " es de tipo '" + tipoAct + "' pero se esperaba '" + tipoEsp + "'.");
          }
        }
      }
    }
pilaSemantica.push(tipoRetorno);
     {if ("" != null) return nodoLlamadaFuncion;}
    throw new Error("Missing return statement in function");
}

/*-- Las operacionen utilizan la precedencia de operadores --*/
// Expresiones de menor orden (+, -, ||)
  final public Arbol expresion() throws ParseException {Arbol izquierda, derecha;
  Token op;
    // El primer operando siempre es mas fuerte, por lo que va a la izquierda.
      izquierda = expresionRelacional();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OP_SUMA:
      case OP_RESTA:
      case OP_OR:{
        ;
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OP_SUMA:{
        op = jj_consume_token(OP_SUMA);
        break;
        }
      case OP_RESTA:{
        op = jj_consume_token(OP_RESTA);
        break;
        }
      case OP_OR:{
        op = jj_consume_token(OP_OR);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      derecha = expresionRelacional();
// Accion sematica obt tipos, validar y empujar
      validarOperacionBinaria(op);
      // Nodo para las operaciones.
      // Nuevo padre.
      Arbol nodoOperacion = new Arbol("Operacion_SUM_RES_OR: " + op.image);

      //sub-árbol anterior (el de la izquierda) como el primer hijo.
      nodoOperacion.agregarHijo(izquierda);

      //Operador
          nodoOperacion.agregarHijo(new Arbol("Token: " + op.image));

      // Operando de la derecha
      nodoOperacion.agregarHijo(derecha);

          // Actualizamos por la izquierda, **puede iterar muchas veces.
          izquierda = nodoOperacion;
    }
{if ("" != null) return izquierda;}
    throw new Error("Missing return statement in function");
}

// Expresiones relacionales (==, !=, <, >, <=, >=)
  final public Arbol expresionRelacional() throws ParseException {Arbol izquierda, derecha;
  Token op;
    // Primer termino (a la izquierda)
      izquierda = termino();
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OP_MENOR_IGUAL:
      case OP_MAYOR_IGUAL:
      case OP_IGUALDAD:
      case OP_DESIGUALDAD:
      case OP_MENOR_QUE:
      case OP_MAYOR_QUE:{
        ;
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OP_IGUALDAD:{
        op = jj_consume_token(OP_IGUALDAD);
        break;
        }
      case OP_DESIGUALDAD:{
        op = jj_consume_token(OP_DESIGUALDAD);
        break;
        }
      case OP_MENOR_QUE:{
        op = jj_consume_token(OP_MENOR_QUE);
        break;
        }
      case OP_MAYOR_QUE:{
        op = jj_consume_token(OP_MAYOR_QUE);
        break;
        }
      case OP_MENOR_IGUAL:{
        op = jj_consume_token(OP_MENOR_IGUAL);
        break;
        }
      case OP_MAYOR_IGUAL:{
        op = jj_consume_token(OP_MAYOR_IGUAL);
        break;
        }
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      // Segundo termino (derecha);
          derecha = termino();
// Pila
          validarOperacionBinaria(op);

      // Nuevo nodo padre (operacion).
      Arbol nodoOperacion = new Arbol("Operador_Relacional" +  op.image);

      // Operando izquierdo
      nodoOperacion.agregarHijo(izquierda);

      // Token del operador
      nodoOperacion.agregarHijo(new Arbol("Token: " + op.image));

          // Operando derecho.
      nodoOperacion.agregarHijo(derecha);

      // Actualizamos (si, otravez) izquierda
      izquierda = nodoOperacion;
    }
{if ("" != null) return izquierda;}
    throw new Error("Missing return statement in function");
}

// Terminos (*, /, %, &&) ej: 3 * 4 + 2 - > (3*4) y 2.
  final public Arbol termino() throws ParseException {Arbol izquierda, derecha;
  Token op;
    // Primer termino
      izquierda = factor();
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OP_MULTI:
      case OP_DIVI:
      case OP_MOD:
      case OP_AND:{
        ;
        break;
        }
      default:
        jj_la1[13] = jj_gen;
        break label_8;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case OP_MULTI:{
        op = jj_consume_token(OP_MULTI);
        break;
        }
      case OP_DIVI:{
        op = jj_consume_token(OP_DIVI);
        break;
        }
      case OP_MOD:{
        op = jj_consume_token(OP_MOD);
        break;
        }
      case OP_AND:{
        op = jj_consume_token(OP_AND);
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      derecha = factor();
//Pila 
      validarOperacionBinaria(op);


          // Nuevo nodo
          Arbol nodoOperacion = new Arbol("Operacion_MUL_DIV_MOD_AND: " + op.image);

      // Acumulamos el mini arbol anterior (la o las rama enteriores).
      nodoOperacion.agregarHijo(izquierda);

      // Token del operador
      nodoOperacion.agregarHijo(new Arbol ("Token: " + op.image));

      // Operando derecho
      nodoOperacion.agregarHijo(derecha);

      // Actualizamos (si, otravez) izquierda
      izquierda = nodoOperacion;
    }
{if ("" != null) return izquierda;}
    throw new Error("Missing return statement in function");
}

// Factores (!, ++, --)
// Operadores primarios (IDs) y operadores unarios
  final public Arbol factor() throws ParseException {Arbol nodo;
  Token t;
  Token parA, parC; // Pal parentesis

    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM_ENTERO:{
      t = jj_consume_token(NUM_ENTERO);
pilaSemantica.push("int"); // Push entero
      {if ("" != null) return new Arbol("Literal_INT: " + t.image);}
      break;
      }
    case NUM_FLOTANTE:{
      t = jj_consume_token(NUM_FLOTANTE);
pilaSemantica.push("float"); // Push flotante
          {if ("" != null) return new Arbol("Literal_FLOAT: " + t.image);}
      break;
      }
    case STR:{
      t = jj_consume_token(STR);
pilaSemantica.push("string"); // Push string
      {if ("" != null) return new Arbol("Literal_CADENA_DE_CARACTERES: " + t.image);}
      break;
      }
    case TRUE:{
      t = jj_consume_token(TRUE);
pilaSemantica.push("bool"); // Push bool
      {if ("" != null) return new Arbol("Literal_BOOL: true");}
      break;
      }
    case FALSE:{
      t = jj_consume_token(FALSE);
pilaSemantica.push("bool"); // Push bool
      {if ("" != null) return new Arbol("Literal_BOOL: false");}
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      if (jj_2_3(2147483647)) {
        nodo = llamadaFuncion();
{if ("" != null) return nodo;}
      } else {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ID:{
          t = jj_consume_token(ID);
Simbolo simboloUsado = tabla.buscar(t.image);
      String tipo = "error"; // Default error

      if (simboloUsado == null)
      {
        registrarError("Error Semantico: L\u00ednea " + t.beginLine + ", columna " + t.beginColumn + " La variable '" + t.image + "' no ha sido declarada.");
      }
      else if (simboloUsado.tipo.equals("funcion"))
      {
         registrarError("Error Semantico: L\u00ednea " + t.beginLine + " La funci\u00f3n '" + t.image + "' debe llamarse con ().");
      }
      else {
         tipo = simboloUsado.tipo;
      }

      pilaSemantica.push(tipo); // PUSH tipo de la variable
      {if ("" != null) return new Arbol("Literal_IDENTIFICADOR: " + t.image);}
          break;
          }
        case PAREN_ABRE:{
          parA = jj_consume_token(PAREN_ABRE);
          nodo = expresion();
          parC = jj_consume_token(PAREN_CIERRA);
Arbol nodoAgrupacion = new Arbol("Agrupacion");
    nodoAgrupacion.agregarHijo(new Arbol("Token: " + parA.image));
    nodoAgrupacion.agregarHijo(nodo);
    nodoAgrupacion.agregarHijo(new Arbol("Token: " + parC.image));
    {if ("" != null) return nodoAgrupacion;}
          break;
          }
        case OP_NOT:{
          t = jj_consume_token(OP_NOT);
          nodo = factor();
String tipoHijo = (String) pilaSemantica.pop();

        // Pa la pila
        if (!tipoHijo.equals("bool") && !tipoHijo.equals("error"))
        {
        registrarError("Error Sem\u00e1ntico: El operador '!' requiere bool, se encontr\u00f3 " + tipoHijo);
        pilaSemantica.push("error");
    } else {
        pilaSemantica.push("bool"); // Bool
    }

    Arbol nodoUnario = new Arbol("Unario_NOT");
    nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
    nodoUnario.agregarHijo(nodo);
    {if ("" != null) return nodoUnario;}
          break;
          }
        case OP_INCREMENTO:{
          t = jj_consume_token(OP_INCREMENTO);
          nodo = factor();
// Pa la pila
    String tipoHijo = (String) pilaSemantica.pop(); // Pila

    if (!tipoHijo.equals("int") && !tipoHijo.equals("float") && !tipoHijo.equals("error"))
    {
        registrarError("Error Sem\u00e1ntico: El operador '++' requiere num\u00e9rico.");
        pilaSemantica.push("error");
    }
    else
    {
        pilaSemantica.push(tipoHijo); // Mantiene el tipo (int++ sigue siendo int)
    }
        // Fin pila

     Arbol nodoUnario = new Arbol("Unario_INC");
     nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
     nodoUnario.agregarHijo(nodo);

     // Validacion para no 1++ o funcion()++
     String nombreNodo = nodo.getNombreProduccion();
     // Solo variables o posi en un vector
     if (!nombreNodo.startsWith("Literal_IDENTIFICADOR") && !nombreNodo.equals("AccesoAlVector"))
     {
         registrarError("Error Sem\u00e1ntico: L\u00ednea " + t.beginLine + ". El operador '++' requiere una variable, no un literal o expresi\u00f3n.");
     }

     {if ("" != null) return nodoUnario;}
          break;
          }
        case OP_DECREMENTO:{
          t = jj_consume_token(OP_DECREMENTO);
          nodo = factor();
// Pila
     String tipoHijo = (String) pilaSemantica.pop();

     if (!tipoHijo.equals("int") && !tipoHijo.equals("float") && !tipoHijo.equals("error"))
     {
         registrarError("Error Sem\u00e1ntico: El operador '--' requiere num\u00e9rico.");
         pilaSemantica.push("error");
     }
     else
     {
         pilaSemantica.push(tipoHijo);
     }
     // Fin pila.

     Arbol nodoUnario = new Arbol("Unario_DEC");
     nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
     nodoUnario.agregarHijo(nodo);

         // Validacion para no 1-- o funcion()--
         String nombreNodo = nodo.getNombreProduccion();
         // Solo variables o posi en un vector
     if (!nombreNodo.startsWith("Literal_IDENTIFICADOR") && !nombreNodo.equals("AccesoAlVector"))
     {
         registrarError("Error Sem\u00e1ntico: L\u00ednea " + t.beginLine +
         ", columna " + t.beginColumn + ". El operador '--' requiere una variable, no un literal o expresi\u00f3n.");
     }

     {if ("" != null) return nodoUnario;}
          break;
          }
        case OP_RESTA:{
          t = jj_consume_token(OP_RESTA);
          nodo = factor();
// Pila
        String tipoHijo = (String) pilaSemantica.pop();
    // Validar numérico
    if (!tipoHijo.equals("int") && !tipoHijo.equals("float") && !tipoHijo.equals("error"))
    {
      registrarError("Error Sem\u00e1ntico: El operador '-' unario requiere num\u00e9rico.");
      pilaSemantica.push("error");
    }
    else
    {
      pilaSemantica.push(tipoHijo);
    }
     // Fin pila

    Arbol nodoUnario = new Arbol("Unario_RESTA");
    nodoUnario.agregarHijo(new Arbol("Token: " + t.image));
    nodoUnario.agregarHijo(nodo);
    {if ("" != null) return nodoUnario;}
          break;
          }
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
    }
    throw new Error("Missing return statement in function");
}

/*-- Fin de las expresiones --*/
  final public 
Arbol declaracionDeVariable() throws ParseException {Arbol nodoDeclaracion = new Arbol("DeclaracionDeVariable");
  Token t_decl, t_dos_puntos, t_id, t_pc, t_asig;
  String tipoDato;
  Arbol exp;
    t_decl = jj_consume_token(VAR);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_decl.image));
    tipoDato = tiposDeDatos();
nodoDeclaracion.agregarHijo(new Arbol("Tipo: " + tipoDato));
    t_dos_puntos = jj_consume_token(DOSPUNTOS);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_dos_puntos.image));
    // Token identificador
      t_id = jj_consume_token(ID);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_id.image));

        Simbolo nuevoSimbolo = new Simbolo(t_id.image, tipoDato, tabla.getAmbitoActual(), t_id.beginLine);
    tabla.insertar(nuevoSimbolo);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OP_ASIGNACION:{
      t_asig = jj_consume_token(OP_ASIGNACION);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_asig.image));
      exp = expresion();
nodoDeclaracion.agregarHijo(exp);
        // Checar que coincida el tipo de dato con lo que se va asignar.**
        String tipoExpr = "error";
        if (!pilaSemantica.estaVacia())
        {
          tipoExpr = (String) pilaSemantica.pop();
        }

        if (!tipoExpr.equals("error"))
        {
          boolean esCompatible = tipoDato.equals(tipoExpr) || (tipoDato.equals("float") && tipoExpr.equals("int"));

          if (!esCompatible)
          {
            registrarError("Error Sem\u00e1ntico: Linea " + t_id.beginLine + ", columna " + t_id.beginColumn +
            " No se puede asignar tipo '" + tipoExpr + "' a variable de tipo '" + tipoDato + "'.");
          }
        }
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    // - > Solo si hay una asignacion.
    
      t_pc = jj_consume_token(PUNTOYCOMA);
nodoDeclaracion.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodoDeclaracion;}
    throw new Error("Missing return statement in function");
}

// print!("Hola mundo");
  final public Arbol salida() throws ParseException {Arbol nodoSalida = new Arbol("SentenciaDeSalida");
        Arbol exp;
        Token t_salida, t_pa, t_pc, t_pyc;
    t_salida = jj_consume_token(SALIDA);
nodoSalida.agregarHijo(new Arbol("Token: " + t_salida.image));
    t_pa = jj_consume_token(PAREN_ABRE);
nodoSalida.agregarHijo(new Arbol("Token: " + t_pa.image));
    exp = expresion();
nodoSalida.agregarHijo(exp);
    if (!pilaSemantica.estaVacia()) pilaSemantica.pop();
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoSalida.agregarHijo(new Arbol("Token: " + t_pc.image));
    t_pyc = jj_consume_token(PUNTOYCOMA);
nodoSalida.agregarHijo(new Arbol("Token: " + t_pyc.image));
{if ("" != null) return nodoSalida;}
    throw new Error("Missing return statement in function");
}

// scan!(operando);
  final public Arbol entrada() throws ParseException {Arbol nodoEntrada = new Arbol("SentenciaDeEntrada");
  Arbol accVector; // Para llenar una posicion en el vector
  Token t_entrada, t_pa, t_id, t_pc, t_pyc;
    t_entrada = jj_consume_token(ENTRADA);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_entrada.image));
    t_pa = jj_consume_token(PAREN_ABRE);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_pa.image));
    if (jj_2_4(2147483647)) {
      accVector = accesoVector();
nodoEntrada.agregarHijo(accVector);
        //  La función accesoVector() ya se encarga de verificar 
        // si el vector existe y si el índice es válido.
        // **********
        if (!pilaSemantica.estaVacia()) pilaSemantica.pop();
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        t_id = jj_consume_token(ID);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_id.image));
          Simbolo simboloEntrada = tabla.buscar(t_id.image);

      if (simboloEntrada == null)
      {
        registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ", columna " + t_id.beginColumn +
        " La variable '" + t_id.image + "' no ha sido declarada");
      }
      else if ("funcion".equals(simboloEntrada.tipo))
      {
        registrarError("Error Semantico: L\u00ednea " + t_id.beginLine +
          " No se puede usar 'scan!' sobre una funci\u00f3n.");
      }
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_pc.image));
    t_pyc = jj_consume_token(PUNTOYCOMA);
nodoEntrada.agregarHijo(new Arbol("Token: " + t_pyc.image));
{if ("" != null) return nodoEntrada;}
    throw new Error("Missing return statement in function");
}

// Vector
  final public Arbol declaracionVector() throws ParseException {Arbol nodoDeclaracionVector = new Arbol("Declarcion_VECTOR");
  String tipoDato;
  Arbol dimensionVector;
  Token t_id, t_pc;
    tipoDato = tiposDeDatos();
nodoDeclaracionVector.agregarHijo(new Arbol("Tipo: " + tipoDato));
    t_id = jj_consume_token(ID);
nodoDeclaracionVector.agregarHijo(new Arbol("ID_Vector: " + t_id.image));
                Simbolo nuevoVector = new Simbolo(t_id.image, "vector", tabla.getAmbitoActual(), t_id.beginLine);
                // com. tipos enteros
                nuevoVector.tipoElemento = tipoDato;
        tabla.insertar(nuevoVector);
    dimensionVector = dimensionVector();
nodoDeclaracionVector.agregarHijo(dimensionVector);
    t_pc = jj_consume_token(PUNTOYCOMA);
nodoDeclaracionVector.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodoDeclaracionVector;}
    throw new Error("Missing return statement in function");
}

  final public Arbol dimensionVector() throws ParseException {Arbol nodoDimensionVector = new Arbol("Dimension_Del_Vector");
        Token t_ca, t_int, t_id, t_cc;
    t_ca = jj_consume_token(CORCHETE_ABRE);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_ca.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM_ENTERO:{
      t_int = jj_consume_token(NUM_ENTERO);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_int.image));
      break;
      }
    case ID:{
      t_id = jj_consume_token(ID);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_id.image));
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t_cc = jj_consume_token(CORCHETE_CIERRA);
nodoDimensionVector.agregarHijo(new Arbol("Token: " + t_cc.image));
{if ("" != null) return nodoDimensionVector;}
    throw new Error("Missing return statement in function");
}

  final public Arbol accesoVector() throws ParseException {Arbol nodoAccesoVec = new Arbol("AccesoAlVEctor");
        Token t_id, t_ca, t_int, t_cc;
    t_id = jj_consume_token(ID);
nodoAccesoVec.agregarHijo(new Arbol("ID_Vector: " + t_id.image));
    Simbolo simboloVector = tabla.buscar(t_id.image);

    if (simboloVector == null)
    {
      /*System.err.println("Error ??? Línea: " + t_id.beginLine + ": El vector '" + t_id.image
        + "' no ha sido declarado.");*/

          registrarError("Error Semantico: L\u00ednea " + t_id.beginLine +  ", columna " + t_id.beginColumn + " El vector '" + t_id.image + "' no ha sido declarado.");
          pilaSemantica.push("error");

    }
    else if (!"vector".equals(simboloVector.tipo))
    {
      /*System.err.println("Error ??? Línea: " + t_id.beginLine + ": El identificador '" + t_id.image
        + "' no es un vector.");*/

      registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ", columna " + t_id.beginColumn + " El identificador '" + t_id.image + "' no es un vector.");
      pilaSemantica.push("error");
    }
    else
    {
      pilaSemantica.push(simboloVector.tipoElemento);
    }
    t_ca = jj_consume_token(CORCHETE_ABRE);
nodoAccesoVec.agregarHijo(new Arbol("Token: " + t_ca.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM_ENTERO:{
      t_int = jj_consume_token(NUM_ENTERO);
nodoAccesoVec.agregarHijo(new Arbol("Literal_INT_Indice: " + t_int.image));
      break;
      }
    case ID:{
      t_id = jj_consume_token(ID);
nodoAccesoVec.agregarHijo(new Arbol("ID_Indice: " + t_id.image));

      Simbolo simboloIndice = tabla.buscar(t_id.image);
      if (simboloIndice == null)
      {
        /*System.err.println("Error ??? Línea: " + t_id.beginLine + ": La variable para el índice '"
          + t_id.image + "' no ha sido declarada.");*/
        registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ", columna " + t_id.beginColumn + " La variable para el indice '" + t_id.image + "' no ha sido declarada.");
      }
      else if (!"int".equals(simboloIndice.tipo))
      {
       /*System.err.println("Error ??? Línea: " + t_id.beginLine
          + ": El índice del vector debe ser de tipo entero, pero se encontró '" + simboloIndice.tipo + "'.");*/
        registrarError("Error Semantico: L\u00ednea " + t_id.beginLine + ", columna " + t_id.beginColumn + " El indice debe ser un entero, pero se encontr\u00f3 un '" + simboloIndice.tipo + "'");
      }
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    t_cc = jj_consume_token(CORCHETE_CIERRA);
nodoAccesoVec.agregarHijo(new Arbol("Token: " + t_cc.image));
{if ("" != null) return nodoAccesoVec;}
    throw new Error("Missing return statement in function");
}

// - > FIN vector

/*-- BUCLES --*/
// For
  final public Arbol bucleFor() throws ParseException {Arbol nodoBucleFor = new Arbol("Bucle_FOR");
  Arbol inicializacion, condicion, actualizacion, bloque;
  Token t_for, t_pa, t_pc, t_pyc1, t_pyc2;
    t_for = jj_consume_token(BUCLE_FOR);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_for.image));
    t_pa = jj_consume_token(PAREN_ABRE);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pa.image));
    inicializacion = inicializacionFor();
nodoBucleFor.agregarHijo(inicializacion);
    t_pyc1 = jj_consume_token(PUNTOYCOMA);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pyc1.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case OP_RESTA:
    case OP_INCREMENTO:
    case OP_DECREMENTO:
    case OP_NOT:
    case PAREN_ABRE:
    case NUM_FLOTANTE:
    case NUM_ENTERO:
    case TRUE:
    case FALSE:
    case ID:
    case STR:{
      condicion = expresion();
nodoBucleFor.agregarHijo(condicion);
        if (!pilaSemantica.estaVacia()) pilaSemantica.pop(); // <--- Agregar POP

      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
    t_pyc2 = jj_consume_token(PUNTOYCOMA);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pyc2.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ID:{
      actualizacion = actualizacionFor();
nodoBucleFor.agregarHijo(actualizacion);
      break;
      }
    default:
      jj_la1[22] = jj_gen;
      ;
    }
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoBucleFor.agregarHijo(new Arbol("Token: " + t_pc.image));
    bloque = bloqueDeCodigo();
nodoBucleFor.agregarHijo(bloque);
{if ("" != null) return nodoBucleFor;}
    throw new Error("Missing return statement in function");
}

// Declaracion e inicializacion de variables en bucles.
  final public Arbol inicializacionFor() throws ParseException {Arbol nodoIniFor = new Arbol("Inicializacion_Bucle_FOR");
  Arbol declVar, asigVar;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VAR:{
      declVar = declaracionDeVariable();
nodoIniFor.agregarHijo(declVar);
           {if ("" != null) return nodoIniFor;}
      break;
      }
    case ID:{
      asigVar = asignacionSinPuntoYComa();
nodoIniFor.agregarHijo(asigVar);
            {if ("" != null) return nodoIniFor;}
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

// Auxiliar
  final public Arbol asignacionSinPuntoYComa() throws ParseException {Arbol nodoAsignacion = new Arbol("AsignacionSinPuntoYComa");
  Arbol accVector, exp;
  Token t_id, t_asig;
    if (jj_2_5(3)) {
      t_id = jj_consume_token(ID);
nodoAsignacion.agregarHijo(new Arbol("ID_Asignacion: " + t_id.image));
      t_asig = jj_consume_token(OP_ASIGNACION);
nodoAsignacion.agregarHijo(new Arbol("Token: " + t_asig.image));
      exp = expresion();
nodoAsignacion.agregarHijo(exp);
          if (!pilaSemantica.estaVacia()) pilaSemantica.pop();
{if ("" != null) return nodoAsignacion;}
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ID:{
        accVector = accesoVector();
nodoAsignacion.agregarHijo(accVector);
        t_asig = jj_consume_token(OP_ASIGNACION);
nodoAsignacion.agregarHijo(new Arbol("Token: " + t_asig.image));
        exp = expresion();
nodoAsignacion.agregarHijo(exp);
      if (!pilaSemantica.estaVacia()) pilaSemantica.pop();
      if (!pilaSemantica.estaVacia()) pilaSemantica.pop();
      {if ("" != null) return nodoAsignacion;}
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    throw new Error("Missing return statement in function");
}

  final public Arbol actualizacionFor() throws ParseException {Arbol nodoActualizacion = new Arbol("Actualizacion_Bucle_FOR");
  Arbol asig;
  Token t_coma;
    // asignaxino.
      asig = asignacionSinPuntoYComa();
nodoActualizacion.agregarHijo(asig);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMA:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_9;
      }
      t_coma = jj_consume_token(COMA);
nodoActualizacion.agregarHijo(new Arbol("Token: " + t_coma.image));
      asig = asignacionSinPuntoYComa();
nodoActualizacion.agregarHijo(asig);
    }
{if ("" != null) return nodoActualizacion;}
    throw new Error("Missing return statement in function");
}

// - > While
  final public Arbol bucleWhile() throws ParseException {Arbol nodoBucleWhile = new Arbol("Bucle_WHILE");
  Arbol condicion, bloque;
  Token t_while, t_pa, t_pc;
    t_while = jj_consume_token(BUCLE_WHILE);
nodoBucleWhile.agregarHijo(new Arbol("Token: " + t_while.image));
    t_pa = jj_consume_token(PAREN_ABRE);
nodoBucleWhile.agregarHijo(new Arbol("Token: " + t_pa.image));
    condicion = expresion();
nodoBucleWhile.agregarHijo(condicion);
String tipoCond = "error";

        if (!pilaSemantica.estaVacia())
        {
      tipoCond = (String) pilaSemantica.pop();
        }

    if (!tipoCond.equals("bool") && !tipoCond.equals("error"))
    {
      registrarError("Error Semantico: La condicion del bucle while debe ser del tipo 'bool', se encontr\u00f3 '" + tipoCond + "'.");
    }
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoBucleWhile.agregarHijo(new Arbol("Token: " + t_pc.image));
    bloque = bloqueDeCodigo();
nodoBucleWhile.agregarHijo(bloque);
{if ("" != null) return nodoBucleWhile;}
    throw new Error("Missing return statement in function");
}

// FIN bucles.

// Condicionales.
// - > If
  final public Arbol condicionalIf() throws ParseException {Arbol nodoIf = new Arbol("Condicional_IF");
  Arbol condicion, bloqueIf, bloqueElse;
  Token t_if, t_pa, t_pc, t_else;
    // "if"
      t_if = jj_consume_token(IF);
nodoIf.agregarHijo(new Arbol("Token: " + t_if.image));
    // "("
      t_pa = jj_consume_token(PAREN_ABRE);
nodoIf.agregarHijo(new Arbol("Token: " + t_pa.image));
    // Condición.
      condicion = expresion();
nodoIf.agregarHijo(condicion);
String tipoCond = "error";
    if (!pilaSemantica.estaVacia())
    {
        tipoCond = (String) pilaSemantica.pop();
    }

    if (!tipoCond.equals("bool") && !tipoCond.equals("error"))
    {
      registrarError("Error Semantico: Linea " + t_pa.beginLine + ", columna" + t_pa.beginColumn +
      " La condicion del if debe ser del tipo 'bool', se encontr\u00f3 '" + tipoCond + "'.");
    }
    // ")"
      t_pc = jj_consume_token(PAREN_CIERRA);
nodoIf.agregarHijo(new Arbol("Token: " + t_pc.image));
    // Codigo que ejecuta el if.
      bloqueIf = bloqueDeCodigo();
nodoIf.agregarHijo(bloqueIf);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      // else
          t_else = jj_consume_token(ELSE);
nodoIf.agregarHijo(new Arbol("Token: " + t_else.image));
nodoIf.agregarHijo(new Arbol("Bloque_ELSE"));
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LLAVE_ABRE:{
        // ELSE { bloqueDeCodigo() }
              bloqueElse = bloqueDeCodigo();
nodoIf.agregarHijo(bloqueElse);
        break;
        }
      case IF:{
        bloqueElse = condicionalIf();
nodoIf.agregarHijo(bloqueElse);
        break;
        }
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[27] = jj_gen;
      ;
    }
{if ("" != null) return nodoIf;}
    throw new Error("Missing return statement in function");
}

  final public Arbol condicionalSwitch() throws ParseException {Arbol nodoSwitch = new Arbol("Condicional_SWITCH");
  Arbol expresionControl, caso, defecto;
  Token t_switch, t_pa, t_pc, t_lla, t_llc;
  String tipoControl;
    t_switch = jj_consume_token(SWITCH);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_switch.image));
    t_pa = jj_consume_token(PAREN_ABRE);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_pa.image));
    expresionControl = expresion();
nodoSwitch.agregarHijo(expresionControl);

    tipoControl = "error";
    if (!pilaSemantica.estaVacia())
    {
        tipoControl = (String) pilaSemantica.pop();
    }
    t_pc = jj_consume_token(PAREN_CIERRA);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_pc.image));
    t_lla = jj_consume_token(LLAVE_ABRE);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_lla.image));
    profundidadSwitch++; // Entrada dde 1 en un switch

    label_10:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CASE_SWITCH:{
        ;
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        break label_10;
      }
      caso = caseSwitch(tipoControl);
nodoSwitch.agregarHijo(caso);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case DEFAULT_SWITCH:{
      defecto = defaultSwitch();
nodoSwitch.agregarHijo(defecto);
      break;
      }
    default:
      jj_la1[29] = jj_gen;
      ;
    }
    t_llc = jj_consume_token(LLAVE_CIERRA);
nodoSwitch.agregarHijo(new Arbol("Token: " + t_llc.image));
    profundidadSwitch--; // <--- escapamos del switch :o.

{if ("" != null) return nodoSwitch;}
    throw new Error("Missing return statement in function");
}

  final public Arbol caseSwitch(String tipoControl) throws ParseException {Arbol nodoCase = new Arbol("Case_SWITCH");
  Arbol sentencia, breakSentencia;
  Token t_case, t_valor, t_dospuntos;
  String tipoValorCase = "error";
    // CASE_CONDICIONAL_SWITCH ("case")
      t_case = jj_consume_token(CASE_SWITCH);
nodoCase.agregarHijo(new Arbol("Token: " + t_case.image));
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM_ENTERO:{
      t_valor = jj_consume_token(NUM_ENTERO);
nodoCase.agregarHijo(new Arbol("Valor_Case_INT: " + t_valor.image));
      tipoValorCase = "int"; // Validar tipo case:

      break;
      }
    case STR:{
      t_valor = jj_consume_token(STR);
nodoCase.agregarHijo(new Arbol("Valor_Case_STRING: " + t_valor.image));
      tipoValorCase = "string"; // Validar tipo case:

      break;
      }
    default:
      jj_la1[30] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
if (!tipoControl.equals("error") && !tipoValorCase.equals(tipoControl)) {
      registrarError("Error Sem\u00e1ntico: L\u00ednea " + t_case.beginLine + ", columna " + t_case.beginColumn + ". El tipo del case ('" +
      tipoValorCase + "') no coincide con el tipo de la expresi\u00f3n del switch ('" + tipoControl + "').");
  }
    t_dospuntos = jj_consume_token(DOSPUNTOS);
nodoCase.agregarHijo(new Arbol("Token: " + t_dospuntos.image));
    label_11:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case IF:
      case SWITCH:
      case BREAK:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case VAR:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        break label_11;
      }
      sentencia = sentencia();
nodoCase.agregarHijo(sentencia);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BREAK:{
      breakSentencia = sentenciaBreak();
nodoCase.agregarHijo(breakSentencia);
      break;
      }
    default:
      jj_la1[32] = jj_gen;
      ;
    }
{if ("" != null) return nodoCase;}
    throw new Error("Missing return statement in function");
}

  final public Arbol sentenciaBreak() throws ParseException {Arbol nodoStmtBreak = new Arbol("SentenciaBreak");
  Token t_break, t_pc;
    t_break = jj_consume_token(BREAK);
nodoStmtBreak.agregarHijo(new Arbol("Token: " + t_break.image));
if (profundidadSwitch == 0)
    {
      registrarError("Error Sem\u00e1ntico: L\u00ednea " + t_break.beginLine +
        ". La sentencia 'break' solo es v\u00e1lida dentro de un 'switch'.");
    }
    t_pc = jj_consume_token(PUNTOYCOMA);
nodoStmtBreak.agregarHijo(new Arbol("Token: " + t_pc.image));
{if ("" != null) return nodoStmtBreak;}
    throw new Error("Missing return statement in function");
}

  final public Arbol defaultSwitch() throws ParseException {Arbol nodoDefault = new Arbol("Default_SWITCH");
  Arbol sentencia, breakSentencia;
  Token t_default, t_dospuntos;
    t_default = jj_consume_token(DEFAULT_SWITCH);
nodoDefault.agregarHijo(new Arbol("Token: " + t_default.image));
    t_dospuntos = jj_consume_token(DOSPUNTOS);
nodoDefault.agregarHijo(new Arbol("Token: " + t_dospuntos.image));
    label_12:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ENTERO:
      case FLOTANTE:
      case BOOLEANO:
      case CHAR:
      case STRING:
      case IF:
      case SWITCH:
      case BREAK:
      case BUCLE_FOR:
      case BUCLE_WHILE:
      case VAR:
      case SALIDA:
      case ENTRADA:
      case RETURN:
      case ID:{
        ;
        break;
        }
      default:
        jj_la1[33] = jj_gen;
        break label_12;
      }
      sentencia = sentencia();
nodoDefault.agregarHijo(sentencia);
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case BREAK:{
      breakSentencia = sentenciaBreak();
nodoDefault.agregarHijo(breakSentencia);
      break;
      }
    default:
      jj_la1[34] = jj_gen;
      ;
    }
{if ("" != null) return nodoDefault;}
    throw new Error("Missing return statement in function");
}

// FIN condicionales.
  final public 
String tiposDeDatos() throws ParseException {//Arbol nodoTipo = new Arbol("TipoDeDato");
  Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ENTERO:{
      t = jj_consume_token(ENTERO);
{if ("" != null) return t.image;}
      break;
      }
    case FLOTANTE:{
      t = jj_consume_token(FLOTANTE);
{if ("" != null) return t.image;}
      break;
      }
    case BOOLEANO:{
      t = jj_consume_token(BOOLEANO);
{if ("" != null) return t.image;}
      break;
      }
    case CHAR:{
      t = jj_consume_token(CHAR);
{if ("" != null) return t.image;}
      break;
      }
    case STRING:{
      t = jj_consume_token(STRING);
{if ("" != null) return t.image;}
      break;
      }
    default:
      jj_la1[35] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3R_factor_1121_5_31()
 {
    if (jj_scan_token(OP_INCREMENTO)) return true;
    return false;
  }

  private boolean jj_3R_factor_1071_5_28()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_llamadaFuncion_835_5_16()
 {
    if (jj_3R_expresion_915_3_15()) return true;
    return false;
  }

  private boolean jj_3R_accesoVector_1400_3_14()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(CORCHETE_ABRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_accesoVector_1432_7_17()) {
    jj_scanpos = xsp;
    if (jj_3R_accesoVector_1433_11_18()) return true;
    }
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_llamadaFuncion_810_3_13()) return true;
    return false;
  }

  private boolean jj_3R_factor_1066_5_27()
 {
    if (jj_3R_llamadaFuncion_810_3_13()) return true;
    return false;
  }

  private boolean jj_3R_accesoVector_1433_11_18()
 {
    if (jj_scan_token(ID)) return true;
    return false;
  }

  private boolean jj_3R_factor_1061_5_26()
 {
    if (jj_scan_token(FALSE)) return true;
    return false;
  }

  private boolean jj_3R_factor_1153_5_32()
 {
    if (jj_scan_token(OP_DECREMENTO)) return true;
    return false;
  }

  private boolean jj_3R_accesoVector_1432_7_17()
 {
    if (jj_scan_token(NUM_ENTERO)) return true;
    return false;
  }

  private boolean jj_3R_factor_1056_5_25()
 {
    if (jj_scan_token(TRUE)) return true;
    return false;
  }

  private boolean jj_3R_factor_1102_5_30()
 {
    if (jj_scan_token(OP_NOT)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(OP_ASIGNACION)) return true;
    if (jj_3R_expresion_915_3_15()) return true;
    return false;
  }

  private boolean jj_3R_expresion_915_3_15()
 {
    if (jj_3R_expresionRelacional_953_3_19()) return true;
    return false;
  }

  private boolean jj_3R_factor_1051_5_24()
 {
    if (jj_scan_token(STR)) return true;
    return false;
  }

  private boolean jj_3R_factor_1046_5_23()
 {
    if (jj_scan_token(NUM_FLOTANTE)) return true;
    return false;
  }

  private boolean jj_3R_factor_1186_5_33()
 {
    if (jj_scan_token(OP_RESTA)) return true;
    return false;
  }

  private boolean jj_3R_factor_1092_5_29()
 {
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  private boolean jj_3R_expresionRelacional_953_3_19()
 {
    if (jj_3R_termino_998_3_20()) return true;
    return false;
  }

  private boolean jj_3R_llamadaFuncion_810_3_13()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_llamadaFuncion_835_5_16()) jj_scanpos = xsp;
    if (jj_scan_token(PAREN_CIERRA)) return true;
    return false;
  }

  private boolean jj_3R_termino_998_3_20()
 {
    if (jj_3R_factor_1041_5_21()) return true;
    return false;
  }

  private boolean jj_3R_factor_1041_5_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_factor_1041_5_22()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1046_5_23()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1051_5_24()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1056_5_25()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1061_5_26()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1066_5_27()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1071_5_28()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1092_5_29()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1102_5_30()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1121_5_31()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1153_5_32()) {
    jj_scanpos = xsp;
    if (jj_3R_factor_1186_5_33()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_factor_1041_5_22()
 {
    if (jj_scan_token(NUM_ENTERO)) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(CORCHETE_ABRE)) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_accesoVector_1400_3_14()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_scan_token(ID)) return true;
    if (jj_scan_token(PAREN_ABRE)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public GramaticaCocoTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[36];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x7c0,0x800,0x7c0,0x7c0,0x7c0,0x0,0x800,0x98400000,0x40600000,0x40600000,0x1f8000,0x1f8000,0x23800000,0x23800000,0x0,0x98400000,0x4000000,0x0,0x0,0x0,0x98400000,0x0,0x0,0x0,0x800,0x0,0x0,0x0,0x0,0x0,0x7c0,0x0,0x7c0,0x0,0x7c0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x20000,0x21d00e5,0x0,0x0,0x21d00e5,0x21d00e5,0x2000000,0x0,0x7e00100,0x0,0x0,0x0,0x0,0x0,0x0,0x5e00000,0x2000100,0x0,0x2000000,0x2400000,0x2400000,0x7e00100,0x2000000,0x2010000,0x2000000,0x0,0x401,0x2,0x8,0x10,0x4400000,0x21d00e5,0x20,0x21d00e5,0x20,0x0,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public GramaticaCoco(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public GramaticaCoco(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new GramaticaCocoTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public GramaticaCoco(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new GramaticaCocoTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new GramaticaCocoTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public GramaticaCoco(GramaticaCocoTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(GramaticaCocoTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 36; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[60];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 36; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 60; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 5; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
