/* Generated By:JavaCC: Do not edit this line. GramaticaCocoConstants.java */
package javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface GramaticaCocoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO = 5;
  /** RegularExpression Id. */
  int ENTERO = 6;
  /** RegularExpression Id. */
  int FLOTANTE = 7;
  /** RegularExpression Id. */
  int BOOLEANO = 8;
  /** RegularExpression Id. */
  int CHAR = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int COMA = 11;
  /** RegularExpression Id. */
  int PUNTOYCOMA = 12;
  /** RegularExpression Id. */
  int DOSPUNTOS = 13;
  /** RegularExpression Id. */
  int FLECHA = 14;
  /** RegularExpression Id. */
  int OP_MENOR_IGUAL = 15;
  /** RegularExpression Id. */
  int OP_MAYOR_IGUAL = 16;
  /** RegularExpression Id. */
  int OP_IGUALDAD = 17;
  /** RegularExpression Id. */
  int OP_DESIGUALDAD = 18;
  /** RegularExpression Id. */
  int OP_MENOR_QUE = 19;
  /** RegularExpression Id. */
  int OP_MAYOR_QUE = 20;
  /** RegularExpression Id. */
  int OP_SUMA = 21;
  /** RegularExpression Id. */
  int OP_RESTA = 22;
  /** RegularExpression Id. */
  int OP_MULTI = 23;
  /** RegularExpression Id. */
  int OP_DIVI = 24;
  /** RegularExpression Id. */
  int OP_MOD = 25;
  /** RegularExpression Id. */
  int OP_ASIGNACION = 26;
  /** RegularExpression Id. */
  int OP_INCREMENTO = 27;
  /** RegularExpression Id. */
  int OP_DECREMENTO = 28;
  /** RegularExpression Id. */
  int OP_AND = 29;
  /** RegularExpression Id. */
  int OP_OR = 30;
  /** RegularExpression Id. */
  int OP_NOT = 31;
  /** RegularExpression Id. */
  int IF = 32;
  /** RegularExpression Id. */
  int ELSE = 33;
  /** RegularExpression Id. */
  int SWITCH = 34;
  /** RegularExpression Id. */
  int CASE_SWITCH = 35;
  /** RegularExpression Id. */
  int DEFAULT_SWITCH = 36;
  /** RegularExpression Id. */
  int BREAK = 37;
  /** RegularExpression Id. */
  int BUCLE_FOR = 38;
  /** RegularExpression Id. */
  int BUCLE_WHILE = 39;
  /** RegularExpression Id. */
  int PAREN_ABRE = 40;
  /** RegularExpression Id. */
  int PAREN_CIERRA = 41;
  /** RegularExpression Id. */
  int LLAVE_ABRE = 42;
  /** RegularExpression Id. */
  int LLAVE_CIERRA = 43;
  /** RegularExpression Id. */
  int CORCHETE_ABRE = 44;
  /** RegularExpression Id. */
  int CORCHETE_CIERRA = 45;
  /** RegularExpression Id. */
  int INICIO = 46;
  /** RegularExpression Id. */
  int FINAL = 47;
  /** RegularExpression Id. */
  int VAR = 48;
  /** RegularExpression Id. */
  int FUNC = 49;
  /** RegularExpression Id. */
  int SALIDA = 50;
  /** RegularExpression Id. */
  int ENTRADA = 51;
  /** RegularExpression Id. */
  int RETURN = 52;
  /** RegularExpression Id. */
  int NUM_FLOTANTE = 53;
  /** RegularExpression Id. */
  int NUM_ENTERO = 54;
  /** RegularExpression Id. */
  int ID = 55;
  /** RegularExpression Id. */
  int STR = 56;
  /** RegularExpression Id. */
  int UNKNOWN = 57;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<COMENTARIO>",
    "\"int\"",
    "\"float\"",
    "\"bool\"",
    "\"char\"",
    "\"string\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"->\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"if\"",
    "\"else\"",
    "\"switch\"",
    "\"case\"",
    "\"default\"",
    "\"break\"",
    "\"for\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"_inicio\"",
    "\"final_\"",
    "\"coco\"",
    "\"fn\"",
    "\"print!\"",
    "\"scan!\"",
    "\"return\"",
    "<NUM_FLOTANTE>",
    "<NUM_ENTERO>",
    "<ID>",
    "<STR>",
    "<UNKNOWN>",
  };

}
